import { Project, Owner } from '@/types';

const OWNERS: Record<string, Owner> = {
  usr_01: {
    id: 'usr_01',
    name: 'Sarah Chen',
    role: 'Staff Platform Engineer',
    email: 'sarah.chen@example.com',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150',
  },
  usr_02: {
    id: 'usr_02',
    name: 'Alex Rivera',
    role: 'Senior Frontend Developer',
    email: 'alex.rivera@example.com',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150',
  },
  usr_03: {
    id: 'usr_03',
    name: 'Priya Sharma',
    role: 'Product Manager',
    email: 'priya.sharma@example.com',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150',
  },
  usr_04: {
    id: 'usr_04',
    name: 'Marcus Vance',
    role: 'Cloud Security Architect',
    email: 'marcus.vance@example.com',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150',
  },
};

export const MOCK_PROJECTS: Project[] = [
  {
    id: 'proj_aurora',
    name: 'Project Aurora - NextGen Data Lakehouse',
    description: 'Migration of legacy analytics pipelines to a unified real-time Lakehouse architecture.',
    customerName: 'Internal Platform',
    status: 'In Progress',
    leadId: 'usr_01',
    owners: [OWNERS.usr_01, OWNERS.usr_04],
    startDate: '2026-06-01',
    targetDate: '2026-11-15',
    lastActivityDate: '2026-08-14T11:15:00Z',
    progressPercentage: 48,
    milestones: [
      {
        id: 'ms_aurora_01',
        title: 'Phase 1: Ingestion & Storage Architecture',
        targetDate: '2026-07-31',
        status: 'Completed',
        tasks: [
          {
            id: 'task_101',
            title: 'Deploy Iceberg REST Catalog on AWS/GCP',
            status: 'Done',
            assignee: OWNERS.usr_01,
            dueDate: '2026-07-25',
            priority: 'High',
          },
          {
            id: 'task_102',
            title: 'Set up IAM and KMS key rotation policies',
            status: 'Done',
            assignee: OWNERS.usr_04,
            dueDate: '2026-07-31',
            priority: 'Critical',
          },
        ],
      },
      {
        id: 'ms_aurora_02',
        title: 'Phase 2: Real-time Streaming & CDC Engine',
        targetDate: '2026-09-30',
        status: 'In Progress',
        tasks: [
          {
            id: 'task_103',
            title: 'Implement Debezium connector for PostgreSQL replica',
            status: 'In Progress',
            assignee: OWNERS.usr_01,
            dueDate: '2026-09-10',
            priority: 'High',
          },
          {
            id: 'task_104',
            title: 'Schema evolution stress testing for Parquet tables',
            status: 'Blocked',
            assignee: OWNERS.usr_01,
            dueDate: '2026-09-20',
            priority: 'Medium',
            isInternalOnly: true,
          },
        ],
      },
      {
        id: 'ms_aurora_03',
        title: 'Phase 3: Query Engine & BI Integration',
        targetDate: '2026-11-15',
        status: 'Upcoming',
        tasks: [
          {
            id: 'task_105',
            title: 'Configure Trino + Spark SQL federation layer',
            status: 'Open',
            assignee: OWNERS.usr_01,
            dueDate: '2026-10-20',
            priority: 'High',
          },
          {
            id: 'task_106',
            title: 'Deliver customer-facing BI connector documentation',
            status: 'Open',
            assignee: OWNERS.usr_03,
            dueDate: '2026-11-10',
            priority: 'Medium',
          },
        ],
      },
    ],
    issues: [
      {
        id: 'i_aurora_01',
        title: 'Schema drift causing Debezium connector failures on staging',
        category: 'Bug',
        priority: 'High',
        status: 'Open',
        linkedMilestoneId: 'ms_aurora_02',
      },
      {
        id: 'i_aurora_02',
        title: 'Compliance: encrypted PII column handling in Parquet',
        category: 'Support',
        priority: 'Critical',
        status: 'Under Review',
        linkedMilestoneId: 'ms_aurora_02',
        isInternalOnly: true,
      },
      {
        id: 'i_aurora_03',
        title: 'Customer requests near-real-time Tableau connector',
        category: 'Feature Request',
        priority: 'Medium',
        status: 'Open',
      },
    ],
    updates: [
      {
        id: 'feed_001',
        timestamp: '2026-08-14T09:30:00Z',
        author: OWNERS.usr_01,
        source: 'slack',
        channel: '#proj-aurora-engineering',
        rawText: 'Quick update on CDC: Ran into schema drift issues when testing the Debezium Postgres connector on staging. Blocked on task_104 until we finalize nested type casting rules. Pinged Marcus to check compliance rules on encrypted columns.',
        summary: 'CDC staging blocked by schema drift in Debezium connector. Awaiting type-casting rule finalization and compliance review on encrypted columns.',
        affectedTaskIds: ['task_104'],
        isCustomerVisible: false,
      },
      {
        id: 'feed_002',
        timestamp: '2026-08-14T11:15:00Z',
        author: OWNERS.usr_04,
        source: 'standup_note',
        channel: 'Async Daily Standup',
        rawText: 'Audited the staging KMS policies. Column-level encryption keys are configured for PII fields. Green light to proceed once type casting fix is merged.',
        summary: 'KMS audit complete - PII column encryption keys confirmed on staging. Unblocked once type-casting PR merges.',
        affectedTaskIds: ['task_104'],
        isCustomerVisible: true,
      },
      {
        id: 'feed_005',
        timestamp: '2026-07-31T16:00:00Z',
        author: OWNERS.usr_01,
        source: 'manual',
        channel: 'Milestone Update',
        rawText: undefined,
        summary: 'Phase 1 complete. Iceberg catalog deployed and KMS policies validated across AWS and GCP.',
        isCustomerVisible: true,
      },
    ],
    documents: [
      { id: 'd_aurora_01', name: 'Aurora_Architecture_v3.pdf', size: '4.1 MB', uploadedAt: '2026-06-10', category: 'Architecture', isCustomerVisible: true },
      { id: 'd_aurora_02', name: 'Lakehouse_SOW_v2.pdf', size: '1.3 MB', uploadedAt: '2026-06-01', category: 'SOW', isCustomerVisible: true },
      { id: 'd_aurora_03', name: 'Internal_KMS_Compliance_Audit.pdf', size: '820 KB', uploadedAt: '2026-08-14', category: 'Report', isCustomerVisible: false },
    ],
  },

  {
    id: 'proj_pulse',
    name: 'Pulse UI - AI Operations Console',
    description: 'Unified internal developer portal for automated incident response and metric forecasting.',
    customerName: 'DevOps Platform',
    status: 'Planning',
    leadId: 'usr_03',
    owners: [OWNERS.usr_03, OWNERS.usr_02],
    startDate: '2026-07-15',
    targetDate: '2026-12-20',
    lastActivityDate: '2026-08-15T08:20:00Z',
    progressPercentage: 22,
    milestones: [
      {
        id: 'ms_pulse_01',
        title: 'Design System & Metric Visualization Engine',
        targetDate: '2026-08-30',
        status: 'In Progress',
        tasks: [
          {
            id: 'task_201',
            title: 'Build dynamic time-series charting components with WebGL',
            status: 'In Progress',
            assignee: OWNERS.usr_02,
            dueDate: '2026-08-22',
            priority: 'High',
          },
          {
            id: 'task_202',
            title: 'Integrate LLM streaming reasoning panel',
            status: 'In Progress',
            assignee: OWNERS.usr_02,
            dueDate: '2026-08-30',
            priority: 'Medium',
          },
          {
            id: 'task_203',
            title: 'Draft PRD for automated root-cause alerting',
            status: 'Done',
            assignee: OWNERS.usr_03,
            dueDate: '2026-08-10',
            priority: 'High',
          },
        ],
      },
      {
        id: 'ms_pulse_02',
        title: 'Incident Response Automation Engine',
        targetDate: '2026-10-15',
        status: 'Upcoming',
        tasks: [
          {
            id: 'task_204',
            title: 'Build runbook auto-trigger from alert webhooks',
            status: 'Open',
            assignee: OWNERS.usr_02,
            dueDate: '2026-10-01',
            priority: 'High',
          },
          {
            id: 'task_205',
            title: 'Integrate on-call schedule with PagerDuty API',
            status: 'Open',
            assignee: OWNERS.usr_03,
            dueDate: '2026-10-10',
            priority: 'Medium',
          },
          {
            id: 'task_206',
            title: 'Internal: cost model for LLM inference at p99 load',
            status: 'Open',
            assignee: OWNERS.usr_04,
            dueDate: '2026-09-20',
            priority: 'Medium',
            isInternalOnly: true,
          },
        ],
      },
      {
        id: 'ms_pulse_03',
        title: 'Beta Launch & Customer Handover',
        targetDate: '2026-12-20',
        status: 'Upcoming',
        tasks: [
          {
            id: 'task_207',
            title: 'Run closed beta with 3 internal engineering teams',
            status: 'Open',
            assignee: OWNERS.usr_03,
            dueDate: '2026-11-30',
            priority: 'High',
          },
          {
            id: 'task_208',
            title: 'Produce user onboarding guide & video walkthrough',
            status: 'Open',
            assignee: OWNERS.usr_02,
            dueDate: '2026-12-15',
            priority: 'Low',
          },
        ],
      },
    ],
    issues: [
      {
        id: 'i_pulse_01',
        title: 'WebGL canvas memory leak on Safari 17',
        category: 'Bug',
        priority: 'High',
        status: 'Under Review',
        linkedMilestoneId: 'ms_pulse_01',
      },
      {
        id: 'i_pulse_02',
        title: 'Customer requests natural language incident summarization',
        category: 'Feature Request',
        priority: 'High',
        status: 'Open',
      },
      {
        id: 'i_pulse_03',
        title: 'LLM panel latency exceeds 3s p95 in load tests',
        category: 'Implementation',
        priority: 'Medium',
        status: 'Open',
        linkedMilestoneId: 'ms_pulse_01',
      },
      {
        id: 'i_pulse_04',
        title: 'Internal: OpenAI token budget review needed for Q4',
        category: 'Question',
        priority: 'Medium',
        status: 'Open',
        isInternalOnly: true,
      },
    ],
    updates: [
      {
        id: 'feed_003',
        timestamp: '2026-08-14T14:45:00Z',
        author: OWNERS.usr_02,
        source: 'github_pr_comment',
        channel: 'PR #142 - WebGL Timeline Canvas',
        rawText: 'Pushed the initial commit for WebGL time-series rendering (task_201). Performance benchmark hit 60fps with 500k data points. Ready for code review from Priya & Sarah.',
        summary: 'WebGL time-series renderer shipped: 60fps at 500k data points. PR #142 ready for review.',
        affectedTaskIds: ['task_201'],
        isCustomerVisible: true,
      },
      {
        id: 'feed_004',
        timestamp: '2026-08-15T08:20:00Z',
        author: OWNERS.usr_03,
        source: 'meeting_summary',
        channel: 'Pulse Executive Sync',
        rawText: 'Met with customer advisory board today. High demand for natural language incident summarization. We are reprioritizing the LLM streaming panel (task_202) to begin this sprint.',
        summary: 'Advisory board: NL incident summarization is top demand. LLM panel reprioritized to current sprint.',
        affectedTaskIds: ['task_202'],
        statusChange: 'In Progress',
        isCustomerVisible: true,
      },
    ],
    documents: [
      { id: 'd_pulse_01', name: 'PulseUI_PRD_v1.pdf', size: '2.2 MB', uploadedAt: '2026-07-20', category: 'SOW', isCustomerVisible: true },
      { id: 'd_pulse_02', name: 'DesignSystem_Figma_Export.pdf', size: '5.8 MB', uploadedAt: '2026-08-05', category: 'Architecture', isCustomerVisible: true },
      { id: 'd_pulse_03', name: 'Internal_LLM_CostModel_Q4.xlsx', size: '340 KB', uploadedAt: '2026-08-15', category: 'Report', isCustomerVisible: false },
    ],
  },
];